### ISSUE TITLE
Not possible to install the package

### ISSUE THREAD

**Issue by MarcoCasanovaAlvarez** [jorgepiloto/lamberthub#50]
I tried to install the package in many different ways but without success, could you give me if I did something wrong?

- First try:
`pip install lamberthub` 

`ERROR: Could not find a version that satisfies the requirement lamberthub (from versions: none)
ERROR: No matching distribution found for lamberthub`

- Second:
 `conda install lamberthub`

`PackagesNotFoundError: The following packages are not available from current channels`

-Third: `pip install https://github.com/jorgepiloto/lamberthub`

- Fourth: `pip install git+git:https://github.com/jorgepiloto/lamberthub`

I am running out of ideas now, do you now how to solve this issue?
Thanks

**Comment by jorgepiloto** [comment]
Hi @MarcoCasanovaAlvarez, thank you for opening this. After creating a new Python 3.8 environment and running:

```
pip install lamberthub
```

using `pip== 21.2.4`, no errors were raised during the installation process. Therefore, let me guide you step by step to guess where the problem might be. Paste the output you get for each one of the steps so we can both debug this.

1. Check your current Python environment by running `which python`. In case you are using Windows OS, previous command should be `where.exe python`.
2. Create a new directory named `test_lamberthub`, change to this directory and run `python -m venv venv`. This will create a new virtual environment named `venv`, so we can be sure no conflicts arise with the Python base installation.
3. Activate this new environment using `source .venv/bin/activate` or `.\venv\Scripts\activate` for Windows OS.
4. Run `pip freeze`. This will show the current version for each package  within the clean environment. You should see at least `pip` and `setuptools` ones.
5. Upgrade `pip` using `pip install -U pip`.
6. Finally run `pip install lamberthub` and check if the same error message appears.

**Comment by astrojuanlu** [comment]
lamberthub is available on PyPI https://pypi.org/project/lamberthub/#files therefore `pip install lamberthub` should work. @MarcoCasanovaAlvarez do you want to paste the complete output of `pip install lamberthub -vvv`, as well as `pip --version`?

**Comment by MarcoCasanovaAlvarez** [comment]
Hi @jorgepiloto and @astrojuanlu, first of all, thank you for the quick response. 

I´ve just updated pip to the last version.
`pip 21.2.4 from c:\users\marco\anaconda3\lib\site-packages\pip (python 3.7)`

but when I run pip install lamberthub -vvv I get this:



It seems a problem 
Using pip 21.2.4 from c:\users\marco\anaconda3\lib\site-packages\pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: C:\Users\marco\AppData\Local\Temp\pip-ephem-wheel-cache-ig0vf4nu
Created temporary directory: C:\Users\marco\AppData\Local\Temp\pip-req-tracker-q1vhxki0
Initialized build tracking at C:\Users\marco\AppData\Local\Temp\pip-req-tracker-q1vhxki0
Created build tracker: C:\Users\marco\AppData\Local\Temp\pip-req-tracker-q1vhxki0
Entered build tracker: C:\Users\marco\AppData\Local\Temp\pip-req-tracker-q1vhxki0
Created temporary directory: C:\Users\marco\AppData\Local\Temp\pip-install-c63gter3
1 location(s) to search for versions of lamberthub:
* https://pypi.org/simple/lamberthub/
Fetching project page and analyzing links: https://pypi.org/simple/lamberthub/
Getting page https://pypi.org/simple/lamberthub/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/lamberthub/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/lamberthub/ HTTP/1.1" 304 0
  Link requires a different Python (3.7.6 not in: '>=3.8'): https://files.pythonhosted.org/packages/4b/29/323f03b5a2add9d209088291e547f58ffaa6d0d1940d6c66b42df6d56e55/lamberthub-0.1-py3-none-any.whl#sha256=0fc060fd5afaaa8a49acae3e47df496527ddcfe43cde8ea93cfe2299f9ed34b8 (from https://pypi.org/simple/lamberthub/) (requires-python:>=3.8)
  Link requires a different Python (3.7.6 not in: '>=3.8'): https://files.pythonhosted.org/packages/71/48/2c0da4cd1b2ac26da641efadb2560f24f383302e12e3139bbe7e776ca94f/lamberthub-0.1.tar.gz#sha256=b8550192fc0d0d5ee8d4d891f2e3f4da63cf60ad93ad41032f635b78e440c4cd (from https://pypi.org/simple/lamberthub/) (requires-python:>=3.8)
Skipping link: not a file: https://pypi.org/simple/lamberthub/
Given no hashes to check 0 links for project 'lamberthub': discarding no candidates
ERROR: Could not find a version that satisfies the requirement lamberthub (from versions: none)
ERROR: No matching distribution found for lamberthub
Exception information:
Traceback (most recent call last):
  File "c:\users\marco\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "c:\users\marco\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('lamberthub')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\marco\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "c:\users\marco\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\users\marco\anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 343, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('lamberthub'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\marco\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "c:\users\marco\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "c:\users\marco\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 316, in run
    reqs, check_supported_wheels=not options.target_dir
  File "c:\users\marco\anaconda3\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 103, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for lamberthub
Removed build tracker: 'C:\\Users\\marco\\AppData\\Local\\Temp\\pip-req-tracker-q1vhxki0'

**Comment by astrojuanlu** [comment]
```
Link requires a different Python (3.7.6 not in: '>=3.8')
```

You need Python 3.8 or newer!

**Comment by astrojuanlu** [comment]
I admit the error message of pip is not very informative though

**Comment by MarcoCasanovaAlvarez** [comment]
That was the problem then! Apologies I didn´t know that requirement. Thanks to both ;)
